[package]
name = "wasm_sprites"
version = "0.1.0"
authors = ["user <user@user.user>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
